#!/bin/env zsh

# prepare lazyload compdef
typeset -a __lazyload_compdefs
compdef () { __lazyload_compdefs=($__lazyload_compdefs "$*") }

# auto start tmux before p10k instant prompt
if [[ "$(uname -s)" == "Darwin" ]]; then
    export PATH="$PATH:/usr/local/bin"
else
    export ZSH_TMUX_AUTOSTART=true
fi
if [[ -r "$HOME/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux/tmux.plugin.zsh" ]]; then
    source $HOME/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux/tmux.plugin.zsh
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export DOTFILES=$HOME/.dotfiles
export ZSH_CUSTOM=$HOME/.zsh
source $ZSH_CUSTOM/antigen.zsh

# load all common configurations
for config_file ($ZSH_CUSTOM/common/*.zsh(N)); do
    source $config_file
done
unset config_file

# load extra configurations
test -e "${HOME}/.extra" && source "$HOME/.extra"

# apply antigen configurations
# remember that all configurations above will be cached
antigen apply

# lazyload completions
function _lazyload_compdefs {
    lazyload_compdefs
    add-zsh-hook -D precmd _lazyload_compdefs
}
add-zsh-hook precmd _lazyload_compdefs

# enable shell integration only when using iTerm2
if [ $commands[timeout] ]
then
    timeout 1 $HOME/.iterm2/it2check && source $HOME/.iterm2/shell-integration
fi

# load extra configurations without cache
test -e "${HOME}/.post-extra" && source "$HOME/.post-extra" || true
